package inputscan

import (
	"fmt"
	"image"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pdfcpu/pdfcpu/pkg/api"
)

// ExtractPDFImages extracts embedded images from a PDF into a temp directory, decodes them,
// and returns the decoded images.
//
// This works well for:
// - PDFs generated by this app (QR PNGs embedded)
// - Scanned/image-only PDFs (page images embedded as XObjects)
func ExtractPDFImages(pdfPath string) ([]image.Image, error) {
	if !IsPDF(pdfPath) {
		return nil, fmt.Errorf("not a PDF: %s", pdfPath)
	}
	tmpDir, err := os.MkdirTemp("", "ssssecret-images-*")
	if err != nil {
		return nil, err
	}
	// Best-effort cleanup after decode.
	defer os.RemoveAll(tmpDir)

	if err := api.ExtractImagesFile(pdfPath, tmpDir, nil, nil); err != nil {
		return nil, err
	}

	paths, err := listFiles(tmpDir)
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	var imgs []image.Image
	for _, p := range paths {
		ext := strings.ToLower(filepath.Ext(p))
		// Skip non-image outputs.
		if ext == "" {
			continue
		}
		if !IsImage(p) {
			// pdfcpu may output .txt or other artifacts; ignore.
			continue
		}
		img, err := DecodeImageFile(p)
		if err != nil {
			// Some embedded formats may not be decodable; ignore and continue.
			continue
		}
		imgs = append(imgs, img)
	}
	if len(imgs) == 0 {
		return nil, fmt.Errorf("no decodable images found in PDF")
	}
	return imgs, nil
}

func listFiles(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		out = append(out, path)
		return nil
	})
	return out, err
}


