package inputscan

import (
	"fmt"
	"image"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	"github.com/pdfcpu/pdfcpu/pkg/api"
)

// ExtractPDFImages extracts embedded images from a PDF into a temp directory, decodes them,
// and returns the decoded images.
//
// This works well for:
// - PDFs generated by this app (QR PNGs embedded)
// - Scanned/image-only PDFs (page images embedded as XObjects)
func ExtractPDFImages(pdfPath string) ([]image.Image, error) {
	if !IsPDF(pdfPath) {
		return nil, fmt.Errorf("not a PDF: %s", pdfPath)
	}
	tmpDir, err := os.MkdirTemp("", "ssssecret-images-*")
	if err != nil {
		return nil, err
	}
	// Best-effort cleanup after decode.
	defer os.RemoveAll(tmpDir)

	if err := api.ExtractImagesFile(pdfPath, tmpDir, nil, nil); err != nil {
		return nil, err
	}

	paths, err := listFiles(tmpDir)
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	var imgs []image.Image
	var unsupported, failed int
	var lastErr error
	for _, p := range paths {
		if !IsImage(p) {
			// pdfcpu may output formats we have no decoder for (e.g. .jpx) or
			// non-image artifacts.
			unsupported++
			continue
		}
		img, err := DecodeImageFile(p)
		if err != nil {
			failed++
			lastErr = err
			continue
		}
		imgs = append(imgs, img)
	}
	if len(imgs) == 0 {
		if lastErr != nil {
			return nil, fmt.Errorf("no decodable images in PDF (%d extracted, %d unsupported format, %d failed to decode; last error: %w)", len(paths), unsupported, failed, lastErr)
		}
		return nil, fmt.Errorf("no decodable images in PDF (%d extracted, %d unsupported format)", len(paths), unsupported)
	}
	return imgs, nil
}

func listFiles(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		out = append(out, path)
		return nil
	})
	return out, err
}


